[package]
name = "hangar-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
ureq = { workspace = true }
tiny_http = { workspace = true }
url = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
dirs = { workspace = true }
libc = { workspace = true }
open = { workspace = true }
